# write a program to input 8 numbers from the user and display all the unique numbers (once). (Hint: use set)

s = set()
n = input("Enter number : ")
s.add(int(n))
n = input("Enter number : ")
s.add(int(n))
n = input("Enter number : ")
s.add(int(n))
n = input("Enter number : ")
s.add(int(n))
n = input("Enter number : ")
s.add(int(n))
n = input("Enter number : ")
s.add(int(n))
n = input("Enter number : ")
s.add(int(n))
n = input("Enter number : ")
s.add(int(n))

print(s)
